if(WIN32 AND CMAKE_BUILD_TYPE STREQUAL "Release")
	add_executable(sfml1.3 WIN32 main.cpp)
	target_compile_features(sfml1.3 PRIVATE cxx_std_17)
	target_link_libraries(sfml1.3 PRIVATE SFML::Window SFML::System SFML::Graphics SFML::Main)
else()
	add_executable(sfml1.3 main.cpp)
	target_compile_features(sfml1.3 PRIVATE cxx_std_17)
	target_link_libraries(sfml1.3 PRIVATE SFML::Window SFML::System SFML::Graphics)
endif()