if(WIN32 AND CMAKE_BUILD_TYPE STREQUAL "Release")
	add_executable(Maksim WIN32 main.cpp)
	target_compile_features(Maksim PRIVATE cxx_std_17)
	target_link_libraries(Maksim PRIVATE SFML::Window SFML::System SFML::Graphics SFML::Main)
else()
	add_executable(Maksim main.cpp)
	target_compile_features(Maksim PRIVATE cxx_std_17)
	target_link_libraries(Maksim PRIVATE SFML::Window SFML::System SFML::Graphics)
endif()